### PR TITLE
feat: Add rule for having one promoted property per line in constructor

### PR DESCRIPTION
**Pull request by provokateurin**
Based on https://github.com/nextcloud/coding-standard/pull/31 to avoid conflicts.

See
https://github.com/erickskrauch/php-cs-fixer-custom-fixers?tab=readme-ov-file#erickskrauchblank_line_before_return
and
https://github.com/erickskrauch/php-cs-fixer-custom-fixers?tab=readme-ov-file#erickskrauchline_break_after_statements.

### CODE REVIEW

**Review by kesselb — DISMISSED** [review]
Nice :+1:

**Review by ChristophWurst — APPROVED** [review]

**Review by kesselb — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Comment by nickvergessen** [comment]
I kind of disagree with this. it forces a lot of empty lines into code and can actually reduce the readability?

**Comment by ChristophWurst** [comment]
Agree after seeing this in action :broken_heart:

**Comment by nickvergessen** [comment]
In Talk it would add 997 new lines :scream:

**Comment by provokateurin** [comment]
> can actually reduce the readability?

For personally not, as I always write my code with these newlines, but sure don't need to force everyone to have this style.
There seemed to be quite some agreement on this though, as the 3 needed reviews came in very fast and without any objections.

**Comment by ChristophWurst** [comment]
> the 3 needed reviews came in very fast and without any objections

approval under influence

**Comment by provokateurin** [comment]
I didn't even look to your table xD

**Pull request merged**
